"""Initial migration

Revision ID: c8d7937b903f
Revises: 
Create Date: 2025-07-07 23:24:18.857409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d7937b903f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_table('servers',
    sa.Column('id', sa.String(250), nullable=False),
    sa.Column('name', sa.String(250), nullable=False),
    sa.Column('ip', sa.String(250), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servers_id'), 'servers', ['id'], unique=False)
    op.create_table('player_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.String(250), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('player_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_counts_id'), 'player_counts', ['id'], unique=False)
    op.create_table('player_snapshot_association',
    sa.Column('player_count_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_count_id'], ['player_counts.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_snapshot_association')
    op.drop_index(op.f('ix_player_counts_id'), table_name='player_counts')
    op.drop_table('player_counts')
    op.drop_index(op.f('ix_servers_id'), table_name='servers')
    op.drop_table('servers')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###