name: Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-asyncio
    
    - name: Create test environment
      run: |
        echo "DATABASE_URL=sqlite:///./test.db" > .env
        # Create a minimal servers.json for tests
        echo '[{"id": "test", "name": "Test Server", "ip": "localhost", "port": 25565}]' > servers.json
    
    - name: Run tests
      run: |
        pytest -v --cov=src --cov-report=term-missing
    
    - name: Generate coverage report
      run: |
        pytest --cov=src --cov-report=html --cov-report=term
        
    - name: Upload coverage reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: coverage-report
        path: htmlcov/